services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - "4500:3000"
    env_file:
      - path: .env
        required: false
    environment:
      NODE_ENV: production
      HOSTNAME: 0.0.0.0
      PORT: 3000
